.TH pious_tabort 3PIOUS "25 January 1995" " " "PIOUS"
.SH NAME
pious_tabort \- abort a user-transaction

.SH SYNOPSIS C
int pious_tabort(void);

.SH SYNOPSIS FORTRAN
subroutine piousftabort(rc)

integer rc

.SH DESCRIPTION
pious_tabort() aborts a user-transaction.  If successful, the effects
of all file write and seek updates performed within the context
of the user-transaction are undone.

The corresponding Fortran function accepts argument values of type integer,
and returns the result code in
.I rc.

Any error implies that the PIOUS system state is inconsistent.

.SH RETURN VALUES
Upon successful completion, a value of PIOUS_OK (0) is returned.
Otherwise, a negative value is returned indicating an error condition.

.SH ERRORS
The following error code values can be returned.

.TP
PIOUS_EINSUF
insufficient system resources to complete operation

.TP
PIOUS_ETPORT
error condition in underlying transport system

.TP
PIOUS_EUNXP
unexpected error condition encountered

.TP
PIOUS_EFATAL
fatal error; check data server error logs


.SH SEE ALSO
pious_tbegin(3PIOUS), pious_tend(3PIOUS), pious_sysinfo(3PIOUS)
